# Form implementation generated from reading ui file 'Final_UI1.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VotingBooth(object):
    def setupUi(self, VotingBooth):
        VotingBooth.setObjectName("VotingBooth")
        VotingBooth.resize(300, 300)
        VotingBooth.setMinimumSize(QtCore.QSize(300, 300))
        VotingBooth.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(parent=VotingBooth)
        self.centralwidget.setObjectName("centralwidget")
        self.Submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(20, 180, 241, 31))
        self.Submit.setObjectName("Submit")
        self.Radio_Jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Radio_Jane.setGeometry(QtCore.QRect(100, 150, 95, 20))
        self.Radio_Jane.setObjectName("Radio_Jane")
        self.buttonGroup = QtWidgets.QButtonGroup(VotingBooth)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Radio_Jane)
        self.Radio_John = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Radio_John.setGeometry(QtCore.QRect(100, 120, 95, 20))
        self.Radio_John.setObjectName("Radio_John")
        self.buttonGroup.addButton(self.Radio_John)
        self.Error = QtWidgets.QLabel(parent=self.centralwidget)
        self.Error.setGeometry(QtCore.QRect(10, 210, 261, 20))
        self.Error.setText("")
        self.Error.setObjectName("Error")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 0, 161, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_2.setObjectName("label_2")
        self.Identificator = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Identificator.setGeometry(QtCore.QRect(80, 60, 161, 22))
        self.Identificator.setObjectName("Identificator")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 90, 161, 20))
        self.label_3.setObjectName("label_3")
        self.display = QtWidgets.QLabel(parent=self.centralwidget)
        self.display.setGeometry(QtCore.QRect(10, 230, 261, 20))
        self.display.setText("")
        self.display.setObjectName("display")
        VotingBooth.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VotingBooth)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 26))
        self.menubar.setObjectName("menubar")
        VotingBooth.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=VotingBooth)
        self.statusbar.setObjectName("statusbar")
        VotingBooth.setStatusBar(self.statusbar)

        self.retranslateUi(VotingBooth)
        QtCore.QMetaObject.connectSlotsByName(VotingBooth)

    def retranslateUi(self, VotingBooth):
        _translate = QtCore.QCoreApplication.translate
        VotingBooth.setWindowTitle(_translate("VotingBooth", "Voting Booth"))
        self.Submit.setText(_translate("VotingBooth", "Finished"))
        self.Radio_Jane.setText(_translate("VotingBooth", "Jane"))
        self.Radio_John.setText(_translate("VotingBooth", "John"))
        self.label.setText(_translate("VotingBooth", "ELECTION APPLICATION"))
        self.label_2.setText(_translate("VotingBooth", "5 digit ID:"))
        self.label_3.setText(_translate("VotingBooth", "Your Candidates"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VotingBooth = QtWidgets.QMainWindow()
    ui = Ui_VotingBooth()
    ui.setupUi(VotingBooth)
    VotingBooth.show()
    sys.exit(app.exec())
